# Generated by Django 2.2.28 on 2026-03-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
