# Generated by Django 2.2.28 on 2026-03-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_userprofile_google_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='google_picture_url',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_images'),
        ),
    ]
