# Generated by Django 2.2.28 on 2026-03-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20260307_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='total_time',
        ),
    ]
