# Generated by Django 2.2.28 on 2026-03-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20260308_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='serving',
            new_name='servings',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
