# Generated by Django 2.2.28 on 2026-03-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20260310_1024'),
        ('recipes', '0007_auto_20260309_0003'),
    ]

    operations = [
    ]
